add new methods and fields in class Proxy
os-nsu/tests pull request #12
Opened 2024-11-30 07:08 UTC by antuanviolin

2024-12-02 12:08 UTC, borodun commented on tests/conftest.py
> +				  proxy_timeout=0)
не используется proxy_timeout

2024-12-02 12:10 UTC, borodun commented on tests/conftest.py
> +def proxy_fixture(project_dir, proxy_bin_name, tmp_path, config_path, log_file_path, proxy_timeout):
Нет такой фикстуры config_path:

```
  @pytest.fixture
  def proxy_fixture(project_dir, proxy_bin_name, tmp_path, config_path, log_file_path, proxy_timeout):
E       fixture 'config_path' not found
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, core_pattern, doctest_namespace, log_file_path, monkeypatch, project_dir, proxy_bin_name, proxy_fixture, proxy_timeout, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

2024-12-02 12:15 UTC, borodun commented on entities/proxy.py
> +		self.tmp_path = tmp_path
Эти пути точно нужно передавать в конструктор? Мне кажется, они производные от project_dir. А tmp_path, кажется, не является частью прокси. Думаю, его можно вернуть как фикстуру в тестах там, где он требуется.

2024-12-02 12:18 UTC, borodun commented on entities/proxy.py
> +	def build_and_run_proxy(self, args=[], make_args=[], extra_env={}, env=None, wait_until_end=True):
Переменные с env назвать бы както попонятнее. make_env и proxy_env?

2024-12-02 12:20 UTC, borodun commented on tests/lab2/test_config.py
>  		wait_until_end=False
Во всех тестах, где с процессом ничего не делается, лучше делать wait_until_end = True, чтобы после не нужно было явно писать wait и communicate. Поправишь?

2024-12-02 12:21 UTC, borodun commented on tests/lab2/test_config.py
>  		line_number, line_content = wait_for_log_message(
Думаю, в эту функцию нужно сразу передавать экземпляр прокси, а не её поля.

2024-12-02 12:24 UTC, borodun commented on tests/lab2/test_config.py
>  	result = build_and_run_proxy(
Нужно передавать экземпляр прокси в эту функцию из build_steps. А методы сборки и тп из класса прокси убрать. Они не относятся к прокси напрямую.

2024-12-02 12:24 UTC, borodun commented on entities/proxy.py
> +		self.last_modified_time = self._get_last_modified_time()
Работа со всеми полями должна идти через геттеры и сеттеры

2024-12-02 12:30 UTC, borodun commented on tests/lab3/test_execution_sanitizers.py
> +	extra_env["UBSAN_OPTIONS"] = f"{extra_env['SANITIZER_OPTIONS']}"
Предлагаю вынести фикс кавычек отдельным ПР. Он нужен как можно раньше. Сделаешь?

2024-12-07 06:09 UTC, borodun requested changes

2024-12-07 06:09 UTC, borodun commented on tests/lab2/test_config.py
> +	proxy.config_path = proxy.tmp_path / "proxy.conf"
Оно точно так обновляется?
Появляются следующие ошибки:
```
ERROR tests/lab2/test_config.py::test_proxy_with_empty_config - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
ERROR tests/lab2/test_config.py::test_proxy_without_config - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
ERROR tests/lab2/test_config.py::test_proxy_with_invalid_config[option_without_equals] - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
ERROR tests/lab2/test_config.py::test_proxy_with_invalid_config[invalid_option = "value"] - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
ERROR tests/lab2/test_config.py::test_proxy_with_invalid_config[correct_option = "missing_quote] - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
ERROR tests/lab2/test_config.py::test_proxy_with_invalid_config[correct_option "no_equals"] - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
ERROR tests/lab2/test_config.py::test_proxy_with_large_config - FileNotFoundError: [Errno 2] No such file or directory: '/home/borodun/git/os-nsu/proxy-grisha/config.conf'
```

Нужно починить

2024-12-09 13:20 UTC, borodun requested changes
1. Почему все еще дублируются методы run_proxy и build_and_run_proxy?
2. Некоторые тесты падают с ERROR: `fixture 'config_path' not found`. Почему не везде переделано на использование proxy_fixture?
3. Некоторые функции уже принимают proxy_fixture, но вызываются без него, см wait_for_log_message в test_logger.py. Надо исправить.

2024-12-10 07:35 UTC, borodun requested changes

2024-12-10 07:35 UTC, borodun commented on entities/proxy.py
> +		self._config_path = config_path
Нужно добавить и log_path

2024-12-10 07:35 UTC, borodun commented on tests/lab2/test_logger.py
> +def test_log_file_creation(proxy_fixture, log_file_path):
Убрать везде фикстуру log_file_path

2024-12-10 07:35 UTC, borodun commented on steps/logger_steps.py
> +            if check_log_file_exists(proxy.log_file_path):
Нет такого поля log_file_path

2024-12-10 07:35 UTC, borodun commented on steps/logger_steps.py
> +    end_time = time.time() + proxy.timeout
Нет такого поля timeout

2024-12-10 07:35 UTC, borodun commented on entities/proxy.py
> +		self._config_path = config_path
Нужно чтобы конфиги заполнялись дефолтными значениями. Надо посмотреть по какому пути прокси ищет конфиг.

2024-12-10 07:35 UTC, borodun commented on entities/proxy.py
> +	def __init__(self, project_dir=None, proxy_bin_name=None, config_path=None, proxy_timeout=0):
Не нужно передавать config_path в конструктор

2024-12-10 07:35 UTC, borodun commented on entities/proxy.py
> +		time.sleep(0.1)
Зачем нужны sleep? Закомментированный код нужен?

2024-12-10 10:22 UTC, antuanviolin commented on entities/proxy.py
> +		time.sleep(0.1)
я сейчас с этим разбираюсь

2024-12-12 10:35 UTC, borodun requested changes

2024-12-12 10:35 UTC, borodun commented on entities/proxy.py
> +		self._log_file_path = log_file_path
Надо сделать аналогично конфигу, а не передавать из аргументов путь до лога. Саму фикстуру log_file_path надо удалить.

2024-12-16 03:00 UTC, borodun approved these changes

2024-12-16 03:00 UTC, merged